server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enable: false
  datasource:
    url: jdbc:mysql://localhost:3307/crud?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    routingKey: crud.produto.routingKey
